version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cloudtaskmq-test-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: cloudtaskmq_test
    volumes:
      - mongodb_test_data:/data/db
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: cloudtaskmq-test-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_test_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mongodb_test_data:
  redis_test_data:
